// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class ContiMessage;
@class ContiMessageBuilder;



@interface ContiMessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ContiMessage_appID @"appId"
#define ContiMessage_categoryID @"categoryId"
#define ContiMessage_funcID @"funcId"
#define ContiMessage_appVersion @"appVersion"
#define ContiMessage_timeStamp @"timeStamp"
#define ContiMessage_token @"token"
#define ContiMessage_data @"data"
#define ContiMessage_pkgID @"pkgId"
#define ContiMessage_pkgIndex @"pkgIndex"
#define ContiMessage_pkgNum @"pkgNum"
#define ContiMessage_isEncryption @"isEncryption"
#define ContiMessage_isCompress @"isCompress"
@interface ContiMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
    BOOL hasPkgIndex_:1;
    BOOL hasPkgNum_:1;
    BOOL hasIsEncryption_:1;
    BOOL hasIsCompress_:1;
    BOOL hasAppId_:1;
    BOOL hasCategoryId_:1;
    BOOL hasFuncId_:1;
    BOOL hasAppVersion_:1;
    BOOL hasTimeStamp_:1;
    BOOL hasToken_:1;
    BOOL hasData_:1;
    BOOL hasPkgId_:1;
    SInt32 pkgIndex;
    SInt32 pkgNum;
    SInt32 isEncryption;
    SInt32 isCompress;
    NSString* appId;
    NSString* categoryId;
    NSString* funcId;
    NSString* appVersion;
    NSString* timeStamp;
    NSString* token;
    NSString* data;
    NSString* pkgId;
}
- (BOOL) hasAppId;
- (BOOL) hasCategoryId;
- (BOOL) hasFuncId;
- (BOOL) hasAppVersion;
- (BOOL) hasTimeStamp;
- (BOOL) hasToken;
- (BOOL) hasData;
- (BOOL) hasPkgId;
- (BOOL) hasPkgIndex;
- (BOOL) hasPkgNum;
- (BOOL) hasIsEncryption;
- (BOOL) hasIsCompress;
@property (readonly, strong) NSString* appId;
@property (readonly, strong) NSString* categoryId;
@property (readonly, strong) NSString* funcId;
@property (readonly, strong) NSString* appVersion;
@property (readonly, strong) NSString* timeStamp;
@property (readonly, strong) NSString* token;
@property (readonly, strong, getter=getData) NSString* data;
@property (readonly, strong) NSString* pkgId;
@property (readonly) SInt32 pkgIndex;
@property (readonly) SInt32 pkgNum;
@property (readonly) SInt32 isEncryption;
@property (readonly) SInt32 isCompress;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContiMessageBuilder*) builder;
+ (ContiMessageBuilder*) builder;
+ (ContiMessageBuilder*) builderWithPrototype:(ContiMessage*) prototype;
- (ContiMessageBuilder*) toBuilder;

+ (ContiMessage*) parseFromData:(NSData*) data;
+ (ContiMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContiMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ContiMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContiMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContiMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContiMessageBuilder : PBGeneratedMessageBuilder {
@private
    ContiMessage* resultContiMessage;
}

- (ContiMessage*) defaultInstance;

- (ContiMessageBuilder*) clear;
- (ContiMessageBuilder*) clone;

- (ContiMessage*) build;
- (ContiMessage*) buildPartial;

- (ContiMessageBuilder*) mergeFrom:(ContiMessage*) other;
- (ContiMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContiMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAppId;
- (NSString*) appId;
- (ContiMessageBuilder*) setAppId:(NSString*) value;
- (ContiMessageBuilder*) clearAppId;

- (BOOL) hasCategoryId;
- (NSString*) categoryId;
- (ContiMessageBuilder*) setCategoryId:(NSString*) value;
- (ContiMessageBuilder*) clearCategoryId;

- (BOOL) hasFuncId;
- (NSString*) funcId;
- (ContiMessageBuilder*) setFuncId:(NSString*) value;
- (ContiMessageBuilder*) clearFuncId;

- (BOOL) hasAppVersion;
- (NSString*) appVersion;
- (ContiMessageBuilder*) setAppVersion:(NSString*) value;
- (ContiMessageBuilder*) clearAppVersion;

- (BOOL) hasTimeStamp;
- (NSString*) timeStamp;
- (ContiMessageBuilder*) setTimeStamp:(NSString*) value;
- (ContiMessageBuilder*) clearTimeStamp;

- (BOOL) hasToken;
- (NSString*) token;
- (ContiMessageBuilder*) setToken:(NSString*) value;
- (ContiMessageBuilder*) clearToken;

- (BOOL) hasData;
- (NSString*) getData;
- (ContiMessageBuilder*) setData:(NSString*) value;
- (ContiMessageBuilder*) clearData;

- (BOOL) hasPkgId;
- (NSString*) pkgId;
- (ContiMessageBuilder*) setPkgId:(NSString*) value;
- (ContiMessageBuilder*) clearPkgId;

- (BOOL) hasPkgIndex;
- (SInt32) pkgIndex;
- (ContiMessageBuilder*) setPkgIndex:(SInt32) value;
- (ContiMessageBuilder*) clearPkgIndex;

- (BOOL) hasPkgNum;
- (SInt32) pkgNum;
- (ContiMessageBuilder*) setPkgNum:(SInt32) value;
- (ContiMessageBuilder*) clearPkgNum;

- (BOOL) hasIsEncryption;
- (SInt32) isEncryption;
- (ContiMessageBuilder*) setIsEncryption:(SInt32) value;
- (ContiMessageBuilder*) clearIsEncryption;

- (BOOL) hasIsCompress;
- (SInt32) isCompress;
- (ContiMessageBuilder*) setIsCompress:(SInt32) value;
- (ContiMessageBuilder*) clearIsCompress;
@end


// @@protoc_insertion_point(global_scope)
